spring.application.name=demo

# Mercado Pago OAuth
mercadopago.client-id=${MP_CLIENT_ID:1702750736997526}
mercadopago.client-secret=${MP_CLIENT_SECRET:jghzrPuGZ3VMK7FYM3LPPyLVY7jqhOdi}
mercadopago.redirect-uri=${MP_REDIRECT_URI:https://afraid-lights-sing.loca.lt/mercadopago/callback}